name: "Create a Simple Workflow"
description: "You will have to create a Simple Workflow"
level: 1
duration: 30
status: 1
photo: "ApplicationServices_AmazonSWF_LARGE.png"
start_point: |
  {
    "Resources" : {
        "SWF": {

        }
    }
  }
